// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRXlooZq6C7zSCVrbTQZeylwOAmiJ0ZiA',
    appId: '1:1025933890227:web:79080ad034ee7189e456c6',
    messagingSenderId: '1025933890227',
    projectId: 'kasirpro-7bed2',
    authDomain: 'kasirpro-7bed2.firebaseapp.com',
    storageBucket: 'kasirpro-7bed2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6TXMhI6HU8TSPXpE2EvFNgsNzkskM2rY',
    appId: '1:1025933890227:android:99aba32e52cf1cb5e456c6',
    messagingSenderId: '1025933890227',
    projectId: 'kasirpro-7bed2',
    storageBucket: 'kasirpro-7bed2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiYxpbzahHnrI2w8sNdAC1keZKFCWqIAA',
    appId: '1:1025933890227:ios:f3856ac10ea20c86e456c6',
    messagingSenderId: '1025933890227',
    projectId: 'kasirpro-7bed2',
    storageBucket: 'kasirpro-7bed2.firebasestorage.app',
    iosBundleId: 'com.example.kasirPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiYxpbzahHnrI2w8sNdAC1keZKFCWqIAA',
    appId: '1:1025933890227:ios:f3856ac10ea20c86e456c6',
    messagingSenderId: '1025933890227',
    projectId: 'kasirpro-7bed2',
    storageBucket: 'kasirpro-7bed2.firebasestorage.app',
    iosBundleId: 'com.example.kasirPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRXlooZq6C7zSCVrbTQZeylwOAmiJ0ZiA',
    appId: '1:1025933890227:web:8dcd1a35138ab871e456c6',
    messagingSenderId: '1025933890227',
    projectId: 'kasirpro-7bed2',
    authDomain: 'kasirpro-7bed2.firebaseapp.com',
    storageBucket: 'kasirpro-7bed2.firebasestorage.app',
  );
}
